---
   
   - copy:  
       content: ""      
       dest: "/etc/sysconfig/network-scripts/ifcfg-br0"
   
      
   - name: creating Br0 file
     blockinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-br0
        block: |
         DEVICE=br0
         BOOTPROTO=static
         ONBOOT=yes
         TYPE=Bridge
         NM_CONTROLLED=no
         IPADDR=10.2.59.220
         NETMASK=255.255.252.0
         GATEWAY=10.2.56.1
         DNS1=10.4.12.160
         DNS2=10.4.12.220
          

...


