---
- hosts: all
  tasks: 
   
      
   - name: creating Br0 file
     blockinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-br1
        block: |
         DEVICE=br1
         TYPE=Bridge
         ONBOOT=yes
         NM_CONTROLLED=no
         BOOTPROTO=none


...

