---
- replace:
      path: 
      regexp: "ROUTER_IP=10.4.14.207"
      replae: "ROUTER_IP={{ipaddress.router}}"

- replace:
      path: 
      regexp: "CONFIG_SERVER=10.4.14.208"
      replae: "CONFIG_SERVER={{ipaddress.config-server}} "


- replace:
      path: 
      regexp: "CLUSTER=cluster"
      replae: "CLUSTER={{clustername}} "


- replace:
      path: 
      regexp: "SMTP_SMART_HOST=smtp.admin.iiit.ac.in"
      replae: "SMTP_SMART_HOST=stpi-router.vlabs.ac.in"
