

##  - name: Exporting proxy
##    command: vzctl exec 1002 export http_proxy="http://proxy.iiit.ac.in:8080" && vzctl exec 1002 export https_proxy="http://proxy.iiit.ac.in:8080" && vzctl exec 1002 yum install openssh -y
##    register: out
##  - debug: var=out.stdout_lines
# - lineinfile:
#     path: /vz/private/1002/etc/yum.conf
#     regexp: '^proxy=http://'
#     line: 'proxy={{ proxy_env.http_proxy }}'
# - replace:
 #    path: /vz/private/1002/etc/yum.conf
 #    regexp: '^proxy=.*'
 #    replace: 'proxy'
  # - name: Check proxy
  #   shell: echo {{proxy_env}}
  #   register: out
  # - debug:
  #    var:  out  
#- include: test.yml
#- name: installing openssh
 # command: vzctl exec 1002 export http_proxy="{{proxy_env.http_proxy}}" && export https_proxy="{{proxy_env.https_proxy}}" && yum install "{{item}}" -y && service sshd start &&  chkconfig sshd on  
 # command: vzctl exec 1002 {{export_proxy}} && yum install "{{item}}" -y && service sshd start && chkconfig sshd on
 # register: out  
#  with_items:
   #       - openssh-server
 #         - openssh-clients  
  #        - openssh
#- debug: 
  #   var: out
- include: installansible.yml
