---
- name: Set root password
  command: vzctl set 1007 --userpasswd root:test

- name: copy interface ifcfg-eth1 file
  copy: src=ifcfg-eth1 dest=/vz/private/1007/etc/sysconfig/network-scripts/

- name:  Network restart
  command: vzctl exec 1007 service network restart
# tasks file for reverse-proxyserver
