---
- hosts: localhost
  become_user: root
  tasks:
      
    - name: fetch all public ssh keys
      shell: cat /vz/private/1009/root/.ssh/id_rsa.pub
      register: ssh_keys
      tags:
        - ssh
    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"
      tags:
        - ssh

    - name: deploy keys on all servers
      authorized_key: user=vlead key="{{ item }}"
      delegate_to: 10.2.59.222
      with_items:
        - 'command="hooks.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty {{ ssh_keys.stdout }}'
      tags:
        - ssh
