---
- hosts: all
  become: yes
  become_method: "sudo"
  tasks:
  - service: 
     name: network
     state: restarted

#  - name: Running brctl show and output="brctl show"
 #   command: ifconfig
  #  register: out

  #- debug: var=out.stdout_lines

  #- name: Runnig 2nd command
   # command: ifconfig
    #register: out
#  - debug: var=out.stdout_lines 
 
  - name: Manager off
    command: chkconfig NetworkManager off
    register: out
  - debug: var=out.stdout_lines   

  - name: Manager on
    command: chkconfig network on
    register: out
  - debug: var=out.stdout_lines

  - name: Running brctl show command
    command: brctl show
    register: out

  - debug: var=out.stdout_lines     

                


...
